//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("demo1.2.3", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "wsSoap11Binding", Namespace = "http://ws")]
public partial class Ws : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback callAPI_to_ArrayOperationCompleted;

    private System.Threading.SendOrPostCallback callAPI_to_serializedStrOperationCompleted;

    /// <remarks/>
    public Ws(String serverIp)
    {
        if (serverIp.EndsWith(".55"))
        {
            this.Url = "http://" + serverIp + "/cimiss-web/services/ws.wsHttpSoap11Endpoint/";
        }
        else
        {
            this.Url = "http://" + serverIp + ":8008/cimiss-web/services/ws.wsHttpSoap11Endpoint/";
        }
    }

    /// <remarks/>
    public event callAPI_to_ArrayCompletedEventHandler callAPI_to_ArrayCompleted;

    /// <remarks/>
    public event callAPI_to_serializedStrCompletedEventHandler callAPI_to_serializedStrCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:callAPI_to_Array", RequestNamespace = "http://ws", ResponseNamespace = "http://ws", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
    public ArrayOfString[] callAPI_to_Array([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string @params)
    {
        object[] results = this.Invoke("callAPI_to_Array", new object[] {
                    @params});
        return ((ArrayOfString[])(results[0]));
    }

    /// <remarks/>
    public void callAPI_to_ArrayAsync(string @params)
    {
        this.callAPI_to_ArrayAsync(@params, null);
    }

    /// <remarks/>
    public void callAPI_to_ArrayAsync(string @params, object userState)
    {
        if ((this.callAPI_to_ArrayOperationCompleted == null))
        {
            this.callAPI_to_ArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OncallAPI_to_ArrayOperationCompleted);
        }
        this.InvokeAsync("callAPI_to_Array", new object[] {
                    @params}, this.callAPI_to_ArrayOperationCompleted, userState);
    }

    private void OncallAPI_to_ArrayOperationCompleted(object arg)
    {
        if ((this.callAPI_to_ArrayCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.callAPI_to_ArrayCompleted(this, new callAPI_to_ArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:callAPI_to_serializedStr", RequestNamespace = "http://ws", ResponseNamespace = "http://ws", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable = true)]
    public string callAPI_to_serializedStr([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string @params)
    {
        object[] results = this.Invoke("callAPI_to_serializedStr", new object[] {
                    @params});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void callAPI_to_serializedStrAsync(string @params)
    {
        this.callAPI_to_serializedStrAsync(@params, null);
    }

    /// <remarks/>
    public void callAPI_to_serializedStrAsync(string @params, object userState)
    {
        if ((this.callAPI_to_serializedStrOperationCompleted == null))
        {
            this.callAPI_to_serializedStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OncallAPI_to_serializedStrOperationCompleted);
        }
        this.InvokeAsync("callAPI_to_serializedStr", new object[] {
                    @params}, this.callAPI_to_serializedStrOperationCompleted, userState);
    }

    private void OncallAPI_to_serializedStrOperationCompleted(object arg)
    {
        if ((this.callAPI_to_serializedStrCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.callAPI_to_serializedStrCompleted(this, new callAPI_to_serializedStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("demo1.2.3", "1.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws")]
public partial class ArrayOfString
{

    private string[] arrayField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("array", IsNullable = true)]
    public string[] array
    {
        get
        {
            return this.arrayField;
        }
        set
        {
            this.arrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("demo1.2.3", "1.0.0.0")]
public delegate void callAPI_to_ArrayCompletedEventHandler(object sender, callAPI_to_ArrayCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("demo1.2.3", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class callAPI_to_ArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal callAPI_to_ArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ArrayOfString[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ArrayOfString[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("demo1.2.3", "1.0.0.0")]
public delegate void callAPI_to_serializedStrCompletedEventHandler(object sender, callAPI_to_serializedStrCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("demo1.2.3", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class callAPI_to_serializedStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal callAPI_to_serializedStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
